// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Fallback for Vercel build: prisma generate doesn't connect to DB, only needs a valid URL.
const databaseUrl =
  process.env.LOCAL_DATABASE_URL ??
  process.env.TURSO_DATABASE_URL ??
  "file:./prisma/dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
